package com.nana.retrofit.service.api.util;

public enum ErrorCode {

	// 10xx -> autorization error
	AUTH_TOKEN_ERROR(10001, "Token error"), AUTH_TOKEN_EMPTY(10002, "Token empty"),
	AUTH_TOKEN_EXPIRED(10003, "Token expired"), AUTH_TOKEN_INVALID(10004, "Token invalid"),
	AUTH_FAILED(10005, "Authetication failed"),
	AUTH_MANDATORY_INVALID(2032050, "INCOMPLETE DATA FOR REDEMPTION SETUP. PLEASE RECHECK"),
	AUTH_PRODUCTS_REDEMTION_UNIT(2032006, "UT TRANSACTION MINIMUM OR MAXIMUM REDEMPTION UNIT INVALID"),
	AUTH_PRODUCTS_AFTER_BALANCE(2032028, "UT TRANSACTION MINIMUM BALANCE AFTER REDEMPTION UNIT INVALID"),
	TRX_FAILED_INSERT(2000034, "TRANSACTION FAILED TO INSERT"),

	AUTH_MANDATORY_SWITCHING_INVALID(2032051, "INCOMPLETE DATA FOR SWITCHING DETAILS. PLEASE RECHECK"),
	AUTH_SWITCHING_UNIT_INVALID(2032014, "UT TRANSACTION MINIMUM OR MAXIMUM SWITCHING UNIT INVALID"),
	AUTH_MIN_SWITCHING_AFTER_BALANCE(2032042, "UT TRANSACTION MINIMUM BALANCE AFTER SWITCHING UNIT INVALID"),
	AUTH_PRODUCTS(9999, "PRODUCTS NOT FOUND"), TRX_SUCCESS(0, "SUCCESS"),

	AUTH_INV_CUSTOMER(2000004, "DATA NOT EXISTS"),
	AUTH_INV_MANDATORY(2032045, "INCOMPLETE DATA FOR INVESTMENT ACCOUNT SETUP. PLEASE RECHECK"),
	AUTH_INV_MAX_LENGTH(2032047, "MAXIMUM LENGTH EXCEEDED"),
	AUTH_INV_ACCOUNT_SAME(2032048, "INSERTION FAILED. INVESTMENT ACCOUNT NUMBER ALREADY EXIST"),
	AUTH_INV_SETTLEMENT_ACCOUNT(2032053, "SETTLEMENT ACCOUNT ID INVALID"),

	AUTH_SUB_MANDATORY_INVALID(2032049, "INCOMPLETE DATA FOR SUBSCRIPTION DETAILS. PLEASE RECHECK"),
	AUTH_SUB_PRODUCTS_CUT_OF_TIME(2032046, "PRODUCT HAS EXCEEDED ITS CUT OFF TIME"), // DAILY_CUT_OFF_TIME
	AUTH_SUB_PRODUCTS_AMOUNT(2032002, "UT TRANSACTION MINIMUM SUBSCRIPTION INVALID"), // MIN_RSP_SUBSCRIPTION_AMOUNT

	AUTH_TRXNO_DUPLICATION(2032054, "TRANSACTION ALREADY SUBMITTED"),
	AUTH_CUST_MANDATORY_INVALID(2032052, "INCOMPLETE DATA FOR CUSTOMER UPDATE SETUP. PLEASE RECHECK"),
	
	COMMON_ERROR(99999, "GENERAL ERROR");

	protected int errorCode;
	protected String errorMsg;

	ErrorCode(int code, String msg) {

		errorCode = code;
		errorMsg = msg;
	}

	public int getErrorCode() {
		return errorCode;
	}

	public String getErrorMsg() {
		return errorMsg;
	}
	
}
